### ISSUE TITLE
Base path is prefixed?

### ISSUE THREAD

**Issue by vanyamil** [spatie/laravel-route-discovery#12]
Just downloaded this package. Testing it out, it seems like all route URLs and names are prefixed with the whole directory path. Example:
`GET|HEAD        c:/repos/project/app/http/controllers/users c:.repos.project.app.http.…`

Is this because I am on WIndows and the drive paths aren't recognized?

**Comment by freekmurze** [comment]
I'd welcome a PR that fixes this for Windows.

**Comment by vanyamil** [comment]
Unfortunately, unsure how to best handle it, but found that using
`Discover::controllers()->in(app_path('Http\\Controllers'));`
rather than 
`Discover::controllers()->in(app_path('Http/Controllers'));`
solves the issue. Seems to be something about SplFileInfo incorrectly handling paths if the forward slash is used.
Probably adding a note to the documentation is best.
