### ISSUE TITLE
First Issue

### ISSUE THREAD

**Issue by khanalpride** [spatie/laravel-route-discovery#5]
I installed this on new project.

I guess, there should be option to exclude files/directories, so they will not be discovered. (I saw many routes from default laravel breeze also added.)

See this:
![image](https://user-images.githubusercontent.com/6267947/149961389-c535334c-9a1e-42dd-934d-d2b58e7ed403.png)

Also when I used this on one route. Added # annotation to ProfileController and loaded profile form page and I saw `request()->user()` was null. (I saw I am currently logged in and on top right it shows logged in user name). It redirected me to dashboard.

**Comment by freekmurze** [comment]
Take a look at the docs on how to only register a handful of routes via either the routes file or the `DoNotDiscover` annotation.

Could you PR a tests for the other error you saw (or a minimal Laravel app that demonstrates the error? Feel feel to create a new issue 👍
