### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by ralphjsmit** [spatie/laravel-route-discovery#7]
Hey Freek, think that you did a great job with this package (again)! Very good idea.

I've just wanted to try it out in a new project, so that I could start using the package for the whole project right away, before the package is officially released.

However, I just can't get it to work. I tried several things, like publishing the config file, adding routes in the `web.php`..
It's just weird.

The project is using a DDD structure, just like Laravel Beyond CRUD.

I have no idea what's going wrong here. So I'm just wondering if the latest version is supposed to work (which I assume)?

Thanks!

**Comment by freekmurze** [comment]
Hi,

Thanks for the kind words on my work. 

The package should just work, I'm using it [on my blog](https://github.com/spatie/freek.dev) if you want to see a good example.

**Comment by ralphjsmit** [comment]
Okay, thanks! Then I'll try again to debug it, not sure why it didn't work initially.
