### ISSUE TITLE
Base traits' methods being discovered

### ISSUE THREAD

**Issue by ijpatricio** [spatie/laravel-route-discovery#8]
Hello!

Really excited to see this package come to life.

I'm so sorry if this is something I overlooked, but I didn't find anything about this.

I went ahead and made the first controller, `WelcomeController`, through the artisan CLI.
The generated controller naturally extends the `App\Http\Controllers\Controller`, which in turn, extends `Illuminate\Routing\Controller` and uses traits.

This is resulting in having a controller with one method, and registering 13 routes. Picture attached.

Is this somewhat expected and let it be?

Would you accept a PR to try and fix this?

![image](https://user-images.githubusercontent.com/26031459/151131834-ebe402cb-b6ed-4ad3-bcff-6c3f41f525ce.png)

**Comment by freekmurze** [comment]
Yeah, I'd welcome a fix for this. We normally don't let extend controllers anything, that's why this problem didn't pop up for us.

**Comment by ijpatricio** [comment]
Yep, makes sense.

I think many people will use the default, and I guess you think the same.

So I'm putting my hands down on this.

Speak soon!

**Comment by freekmurze** [comment]
We'll handle this further in the PR.
